### ISSUE TITLE
yd-go doesn't show on tint2 systray

### ISSUE THREAD

**Issue by josconvolto** [slytomcat/yd-go#22]
OS: linux mint 2021.2
xfce-panel whithout systray
tint2 shows other apps in systray, but when I run yd-go from terminal I get: 
`systray error: failed to register our icon with the notifier watcher (maybe no tray is running?): The name org.kde.StatusNotifierWatcher was not provided by any .service files`
If xfce systray is enabled I see the app
And... with xfce systray eanbled: at login I see notifications but there is no icon in systray

**Comment by slytomcat** [comment]
Can you clarify how the yd-go starts at login?

I common it seems as racing condition on start of systray service and yd-go.
The simplest way to solve such issues to start yd-go little later (just add `sleep 1`  before starting yd-go).

**Comment by josconvolto** [comment]
In xfce there is the possibility to start a program when, after login user/psw, xfce-session is executed. I don't know the order in which each program starts or whether it is timerd between runs.
Anyway, now I try to start yd-go last by putting it in ~/xinitrc. I will let you know

**Comment by josconvolto** [comment]
I found a solution that satisfies me. yd-go is always in "start at starup", what was missing was the systray in the xfce panel. Now, when I open an application that requires the use of yandex-disk, I don't see the yd-go icon in the panel but I see the start and then end synchronization notification. And that is enough for me.
