### ISSUE TITLE
Странный вид иконки

### ISSUE THREAD

**Issue by avmaksimov** [slytomcat/yd-go#27]
Выглядит очень странно. Как будто одна тень от неё.

Light theme выключена:
![image](https://user-images.githubusercontent.com/2793938/221400978-8cfce03f-8145-4d1b-aea2-b8b5b451fe5a.png)

Light theme включена:
![image](https://user-images.githubusercontent.com/2793938/221400965-5e4e6574-e44e-48d1-b586-7d48ef9208a8.png)

**Comment by slytomcat** [comment]
А что странного?
Иконки yd-go сделаны (в угоду последним трендам дизайна) более простыми и более контрастными (если сравнивать с иконками yandex-disk-indicator).
На темной панели, с отключенной Light theme - все ок.
Иконки с включенной Light theme предназначены для светлой панели и там этой тени нет (не видно).

**Comment by avmaksimov** [comment]
Этим трендам из присутствующих только Ferdium прислушивается, судя по всему. ОК, вам решать.
