### ISSUE TITLE
gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0'

### ISSUE THREAD

**Issue by ulcuber** [slytomcat/yd-go#8]
Occurs sometimes in unknown conditions

```log
20:47:34.230985 ydisk.go:303: D: Daemon already started
20:47:34.312719 ydisk.go:246: D: Timer interval: 1
20:47:34.317608 ydisk.go:260: D: Change:  unknown > idle S true L 10 E false
20:47:34.317821 yd.go:230: D: Last synchronized length: 10
20:47:34.317837 yd.go:251: D: Change handled

(yd-go:22925): Gdk-CRITICAL **: 20:47:34.346: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
20:47:36.314858 ydisk.go:246: D: Timer interval: 2
20:47:40.318519 ydisk.go:246: D: Timer interval: 4
```

OS: Gentoo
Kernel: x86_64 Linux 5.10.76-gentoo-r1
Installed: `x11-libs/gtk+-3.24.31`, `dev-libs/libappindicator-12.10.1_p20200706`

**Comment by slytomcat** [comment]
Does the indicator works in such conditons?

I've already seen such or similar messages, but they don't affect the work of indicator (at least in my environment).

**Comment by ulcuber** [comment]
@slytomcat Yes, it works

**Comment by slytomcat** [comment]
Then just ignore such warnings.

BTW now I'm working on version that is undepended on GTK (it uses D-Bus for creation icon and menu in notification panel area). It is still not stable but I hope I'll mange to fix all major issues soon.

Can I ask you to test that new version in Your environment as soon as it became more stable?

**Comment by slytomcat** [comment]
https://github.com/slytomcat/yd-go/releases/download/master-29231cca/yd-go-dbus - it is bitnary of current D-Bus version.
Or you can build it yourself from this brunch: https://github.com/slytomcat/yd-go/tree/switch-to-fyne-io

**Comment by ulcuber** [comment]
@slytomcat Tried D-Bus version:
```
2022/05/10 14:37:45 systray error: failed to register our icon with the notifier watcher (maybe no tray is running?): The name org.kde.StatusNotifierWatcher was not provided by any .service files
```
Does it require KDE? I am using `i3` Windows Manager.

**Comment by slytomcat** [comment]
org.kde.StatusNotifierWatcher - is the name of status notification area service on D-Bus. I'm not sure witch component of i3 WM can provide this service. Usually it provide status notification icon on such app as Telegram (desktop version) or zoom.

My googling fo several minutes get only i3bar and i3status as main tools for different status notifications but there is also big choice of different extensions for them...
